### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by chibbi** [MSterczewski/Timberborn-RandomMapGenerator#3]
There are no updates, no commits, not even messages on the issues, so i guess this repo is abandoned.

If not, i would love to get an answer here.
Also if this needs a new maintainer, i think i could take care of it (at least more than the current maintainer/owner).

**Comment by sapioit** [comment]
Being on Github, you can always fork it and continue it's development. Those few months without any reply from the author are a sign that the author has abandoned this project.

**Comment by chibbi** [comment]
He didn't set a license and without license you technically have to ask him for permission

**Comment by sapioit** [comment]
There has to be some kind of law or rule about what to do with abandoned property. Even for intellectual property, you have to actively deny people to copy it, and the author is definitely not doing that right now. So I think it would be safe to modify.

If you don't want to take the risk, do check out this other Timberborn map-making mod, with an active developer: 

https://github.com/R-T-B/TimberbornTerrainGenerator

**Comment by chibbi** [comment]
well if there is a map making mod i am happy. i wanted to try it out before answering but i didn't get around to it, busy couple of days.
